### PR TITLE
Tweak graphviz layout

### PR DESCRIPTION
**Pull request by szagoruyko**
looks better like this I think, example here https://github.com/szagoruyko/iterm.torch/pull/4

### CODE REVIEW

**Comment by fmassa** [comment]
I was thinking about it, what about letting the user customise the display options by passing it as an argument ? The thing about filled boxes is that it's impossible to read the content if the color is dark

**Comment by szagoruyko** [comment]
@fmassa yeah the dot function I wrote for iterm lets user pass his own options. we could remove dark colours here though

**Comment by fmassa** [comment]
I actually think that we would also need to use the complementary color (or something like that) for the text if we want filled rectangles, there are lots of cases where the reading is way harder...
But I'll happily accept this PR if you pass the display properties inside the `opts` field (inside say a `display` table), and use it instead. Could you do that ?

**Comment by fmassa** [comment]
I'm merging this in, and I'll add the customizations in a separate commit.

**Comment by fmassa** [comment]
Thanks Sergey !

**Pull request merged**
